In [11]:
data = [i*2 for i in range(100)]

In [13]:
len(data)

100

In [12]:
len(data)

100

In [1]:
%run Python-project/first.py

hello, machine learning!


In [2]:
%timeit L = [i**2 for i in range(1000)]

343 µs ± 4.63 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [3]:
%timeit L = [i**2 for i in range(10000)]

3.47 ms ± 59.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [4]:
%%timeit 
L = []
for n in range(1000):
    L.append(n ** 2)

402 µs ± 8.68 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python

In [6]:
%run?


Docstring:
Run the named file inside IPython as a program.

Usage::

  %run [-n -i -e -G]
       [( -t [-N<N>] | -d [-b<N>] | -p [profile options] )]
       ( -m mod | file ) [args]

Parameters after the filename are passed as command-line arguments to
the program (put in sys.argv). Then, control returns to IPython's
prompt.

This is similar to running at a system prompt ``python file args``,
but with the advantage of giving you IPython's tracebacks, and of
loading all variables into your interactive namespace for further use
(unless -p is used, see below).

The file is executed in a namespace initially consisting only of
``__name__=='__main__'`` and sys.argv constructed as indicated. It thus
sees its environment as if it were being run as a stand-alone program
(except for sharing global objects such as previously imported
modules). But after execution, the IPython interactive namespace gets
updated with all variables defined in the program (except for __name__
and sys.argv). This allo

In [7]:
import numpy

In [8]:
numpy.__version__

'1.13.3'

In [9]:
import numpy as np

In [10]:
np.__version__

'1.13.3'

In [13]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
L[5] = "machine learning"

In [15]:
L

[0, 1, 2, 3, 4, 'machine learning', 6, 7, 8, 9]

In [16]:
import array

In [17]:
arr = array.array("i", [i for i in range(10)]);

In [18]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[5]

In [19]:
nparr = np.array([i for i in range(10)])

In [20]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
nparr[5]

5

In [22]:
nparr[5] = 100

In [23]:
nparr

array([  0,   1,   2,   3,   4, 100,   6,   7,   8,   9])

In [27]:
nparr.dtype

dtype('int64')

In [25]:
nparr[5] = 5.0

In [26]:
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [29]:
np.zeros(10).dtype

dtype('float64')

In [30]:
 np.linspace(0, 20, 10)

array([  0.        ,   2.22222222,   4.44444444,   6.66666667,
         8.88888889,  11.11111111,  13.33333333,  15.55555556,
        17.77777778,  20.        ])

In [31]:
np.random.randint(0, 10)

7

In [32]:
np.random.randint(0, 10, 10)

array([7, 2, 9, 0, 8, 0, 1, 0, 7, 7])

In [33]:
np.random.randint(0, 1, 10)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [34]:
np.random.seed(666)

In [35]:
np.random.randint(3, 5, size=(3, 5))

array([[3, 3, 4, 3, 3],
       [3, 4, 3, 3, 4],
       [4, 3, 4, 3, 4]])

In [36]:
np.random.randint(3, 5, size=(3, 5))

array([[3, 3, 4, 4, 3],
       [3, 3, 4, 4, 3],
       [3, 4, 4, 4, 4]])

In [37]:
np.random.random(10)

array([ 0.77447945,  0.00510884,  0.11285765,  0.11095367,  0.24766823,
        0.0232363 ,  0.72732115,  0.34003494,  0.19750316,  0.90917959])

In [39]:
np.random.normal(10, 100, size = (3, 5))

array([[  12.80167238,   50.8557194 ,   63.92856473, -144.98470081,
          82.9464519 ],
       [ -22.69547657,  124.13367716,   55.24366191, -213.49687669,
         137.04776598],
       [ -62.92882099,  145.9252547 , -110.99026555,    5.38172775,
         -34.11824366]])

In [40]:
np.random.normal?

Docstring:
normal(loc=0.0, scale=1.0, size=None)

Draw random samples from a normal (Gaussian) distribution.

The probability density function of the normal distribution, first
derived by De Moivre and 200 years later by both Gauss and Laplace
independently [2]_, is often called the bell curve because of
its characteristic shape (see the example below).

The normal distributions occurs often in nature.  For example, it
describes the commonly occurring distribution of samples influenced
by a large number of tiny, random disturbances, each with its own
unique distribution [2]_.

Parameters
----------
loc : float or array_like of floats
    Mean ("centre") of the distribution.
scale : float or array_like of floats
    Standard deviation (spread or "width") of the distribution.
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  If size is ``None`` (default),
    a single value is returned if ``loc`

In [41]:
np.random?

Type:        module
String form: <module 'numpy.random' from '/Users/huangting/anaconda3/lib/python3.6/site-packages/numpy/random/__init__.py'>
File:        ~/anaconda3/lib/python3.6/site-packages/numpy/random/__init__.py
Docstring:  
Random Number Generation

==================== =========================================================
Utility functions
random_sample        Uniformly distributed floats over ``[0, 1)``.
random               Alias for `random_sample`.
bytes                Uniformly distributed random bytes.
random_integers      Uniformly distributed integers in a given range.
permutation          Randomly permute a sequence / generate a random sequence.
shuffle              Randomly permute a sequence in place.
seed                 Seed the random number generator.
choice               Random sample from 1-D array.

==================== =========================================================

==================== ======================================================

In [43]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)
    
    Draw random samples from a normal (Gaussian) distribution.
    
    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).
    
    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.
    
    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") of the distribution.
    scale : float or array_like of floats
        Standard deviation (spread or "width") of the distribution.
    size : int or tuple of ints, optional
        Output shap

In [44]:
x = np.arange(10)

In [45]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [49]:
x.ndim

1

In [50]:
X.ndim

2

In [51]:
x.shape

(10,)

In [52]:
X.shape

(3, 5)

In [53]:
x.size

10

In [54]:
X.size

15

In [55]:
x[0]

0

In [56]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [57]:
X[0][0]

0

In [58]:
X[(0,0)]

0

In [59]:
X[0,0]

0

In [60]:
x[0:5]

array([0, 1, 2, 3, 4])

In [61]:
x[:6]

array([0, 1, 2, 3, 4, 5])

In [62]:
x[5:]

array([5, 6, 7, 8, 9])

In [63]:
x[::2]

array([0, 2, 4, 6, 8])

In [64]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
X 